[package]
name = "git_rev"
version = "0.1.0"
authors = ["Sam Crow <scrow@eng.ucsd.edu>"]
edition = "2018"
description = "Procedural macros for including git revision hashes in code"
license = "0BSD"
repository = "https://github.com/samcrow/git_rev.rs"

[dependencies]

[lib]
proc-macro = true
